"""
Django settings for limunatv project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from django.core.management.utils import get_random_secret_key

# Helper function to get secrets
def get_secret_or_env(key, default=None):
    """Get value from environment variable or return default"""
    return os.environ.get(key, default)

# Try to import advanced secret management if available
try:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
    from utils_keyvault import get_secret_or_env
except ImportError:
    pass  # Fall back to basic env var access

# Initialize Sentry for error tracking and security monitoring (optional)
try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    
    sentry_dsn = get_secret_or_env('SENTRY_DSN', os.environ.get('SENTRY_DSN', None))
    if sentry_dsn:
        sentry_sdk.init(
            dsn=sentry_dsn,
            integrations=[DjangoIntegration()],
            # Set trace sample rate in production to avoid excessive data; 1.0 = 100% (debug only).
            traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
            # Attach stack traces for better debugging
            attach_stacktrace=True,
            # Enable Django signals for better transaction tracing
            auto_session_tracking=True,
        )
except ImportError:
    pass  # Sentry SDK not installed, skipping error tracking initialization

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY: load sensitive values from environment variables or Azure Key Vault
# In production set `DJANGO_SECRET_KEY`, `DJANGO_DEBUG`, and `DJANGO_ALLOWED_HOSTS`.
# For Key Vault: set AZURE_KEYVAULT_NAME env var (uses Managed Identity or service principal credentials)
SECRET_KEY = get_secret_or_env('DJANGO_SECRET_KEY', os.environ.get('DJANGO_SECRET_KEY', get_random_secret_key()))

# DEBUG should be False in production. Use env var 'DJANGO_DEBUG' to enable when needed.
# On Render, enable DEBUG if not explicitly set to see errors
IS_RENDER = os.environ.get('RENDER') == 'true'
DEBUG = os.environ.get('DJANGO_DEBUG', 'true' if IS_RENDER else 'False').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS must be set in production. On Render, accept all hosts during debugging.
if os.environ.get('DJANGO_ALLOWED_HOSTS'):
    ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS').split(',')
elif IS_RENDER:
    ALLOWED_HOSTS = ['*']  # Accept all hosts on Render during initial debugging
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# CORS configuration for React Native / Expo frontend
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Local development
    'http://localhost:8081',  # Expo dev server
    'http://127.0.0.1:3000',
    'http://127.0.0.1:8081',
]

# For production, add your frontend URLs from environment variable
if frontend_origins := os.environ.get('CORS_ALLOWED_ORIGINS'):
    CORS_ALLOWED_ORIGINS.extend(frontend_origins.split(','))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Add optional apps if available
try:
    import csp
    INSTALLED_APPS.append('csp')
except ImportError:
    pass

try:
    import corsheaders
    INSTALLED_APPS.append('corsheaders')
except ImportError:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]

# Add WhiteNoise for static files in production
if not DEBUG:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')

# Add CORS middleware early if available
try:
    import corsheaders
    MIDDLEWARE.append('corsheaders.middleware.CorsMiddleware')
except ImportError:
    pass

# Add remaining core middleware
MIDDLEWARE.extend([
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
])

# Add CSP middleware if available
try:
    import csp
    MIDDLEWARE.append('csp.middleware.CSPMiddleware')
except ImportError:
    pass

ROOT_URLCONF = 'limunatv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'limunatv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise for serving static files in production
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# ------------------ Security hardening defaults ------------------
# Cookie security (disabled in DEBUG for easier development)
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
else:
    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

# XSS and content sniffing protection
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Clickjacking protection
X_FRAME_OPTIONS = 'DENY'

# HSTS (set to 0 when DEBUG=True)
SECURE_HSTS_SECONDS = 0 if DEBUG else int(os.environ.get('DJANGO_HSTS_SECONDS', '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = True

# Redirect all non-HTTPS to HTTPS in production
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 'yes')

# If you're behind a proxy/load balancer that sets X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Optionally allow CSRF trusted origins via `DJANGO_CSRF_TRUSTED_ORIGINS` env var
csfr_origins = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if csfr_origins:
    CSRF_TRUSTED_ORIGINS = [o for o in csfr_origins.split(',') if o]

# Ensure a sensible default for new Django versions
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------ Content Security Policy (CSP, django-csp 4.0+) ------------------
# Start in report-only mode, iterate and tighten before enforcing.
# See https://github.com/mozilla/django-csp for configuration options.
csp_report_only = os.environ.get('DJANGO_CSP_REPORT_ONLY', 'False').lower() in ('true','1','yes')
csp_report_uri = os.environ.get('DJANGO_CSP_REPORT_URI', '') or '/csp-report/'

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src': ("'self'", 'https://cdnjs.cloudflare.com'),
        'style-src': ("'self'", 'https://fonts.googleapis.com', 'https://cdnjs.cloudflare.com'),
        'font-src': ("'self'", 'https://fonts.gstatic.com'),
        'img-src': ("'self'", 'data:'),
        'connect-src': ("'self'",),
        'report-uri': csp_report_uri,
    },
    'REPORT_ONLY': csp_report_only,
}

# If you want to send reports to a remote collector, set the env var
# `DJANGO_CSP_REPORT_URI` to an https endpoint before turning on enforcement.

# ------------------ Logging for CSP reports ------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if DEBUG else 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'csp': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
